import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
// Generated by `prisma generate --schema prisma/schema.public.prisma`.
import { PrismaClient as PublicPrismaClient } from '../../node_modules/.prisma/client-public';

/**
 * Registry (public-schema) Prisma client — the 37 non-tenant models:
 * Studio, UserIdentity, sessions, SubscriptionPlan, Invoice, AppUser*, Referral*.
 *
 * These tables are shared across all gyms and live in the `public` schema, so a
 * single long-lived client is correct. Tenant models are NOT reachable here —
 * use `TenantPrisma` for those.
 */
@Injectable()
export class PublicPrismaService extends PublicPrismaClient implements OnModuleInit, OnModuleDestroy {
  async onModuleInit(): Promise<void> {
    await this.$connect();
  }

  async onModuleDestroy(): Promise<void> {
    await this.$disconnect();
  }
}
