import { Injectable, InternalServerErrorException } from '@nestjs/common';
import { TenantClientFactory } from './tenant-client.factory';
import { getTenantSchema } from '../common/tenant-context';
// Generated by `prisma generate --schema prisma/schema.tenant.prisma`.
import type { PrismaClient as TenantPrismaClient } from '../../node_modules/.prisma/client-tenant';

/**
 * Request-scoped accessor for the CURRENT gym's tenant client.
 *
 * Services call `this.tenant.client.member.findMany(...)`. The schema comes from
 * `TenantStore.schemaName` (resolved from the registry by the tenant middleware),
 * NOT from a transform of `gym_id` — see TenantClientFactory for why.
 *
 * Because each gym's schema is physically separate, queries here are isolated by
 * construction; an explicit `gym_id` WHERE filter is no longer the load-bearing
 * isolation (though the columns remain for now).
 */
@Injectable()
export class TenantPrisma {
  constructor(private readonly factory: TenantClientFactory) {}

  /** The tenant client bound to the current request's gym schema. */
  get client(): TenantPrismaClient {
    const schema = getTenantSchema();
    if (!schema) {
      throw new InternalServerErrorException(
        'TenantPrisma accessed without tenant context (no schemaName in TenantStore)',
      );
    }
    return this.factory.forSchema(schema);
  }
}
