import { Injectable, OnModuleDestroy, Logger, BadRequestException } from '@nestjs/common';
// Generated by `prisma generate --schema prisma/schema.tenant.prisma`.
// Output dir is set in that schema's generator block.
import { PrismaClient as TenantPrismaClient } from '../../node_modules/.prisma/client-tenant';

/**
 * ────────────────────────────────────────────────────────────────────────────
 * TENANT CLIENT FACTORY — per-gym physical-schema routing (Road B)
 * ────────────────────────────────────────────────────────────────────────────
 *
 * Each gym's data lives in its own Postgres schema (`studio_<gym_uuid>`). The
 * generated tenant client embeds the schema in its CONNECTION STRING
 * (`?schema=studio_<gym>`), so a client can ONLY ever read/write its own gym's
 * schema. There is no per-request `search_path` mutation and therefore no shared
 * mutable state that could leak across concurrent requests.
 *
 * Isolation is proven by scripts/_phase2_isolation_test.js (100 concurrent
 * interleaved queries, zero cross-gym leak).
 *
 * Clients are cached one-per-schema (not one-per-request) to avoid connection
 * churn. `connection_limit` is kept small so total connections stay bounded as
 * gym count grows; revisit with an LRU/eviction policy at high tenant counts.
 */

/**
 * A tenant schema name is ALWAYS `studio_` + a UUID with dashes→underscores.
 *
 * IMPORTANT: the schema name is NOT derivable from `gym_id`. Onboarding sets
 * `studios.schema_name = studio_<owner_user_id>`, which differs from the studio
 * id (`gym_id`). So the canonical source of a request's schema is the registry
 * lookup carried in `TenantStore.schemaName` — never a transform of `gym_id`.
 */
const TENANT_SCHEMA_RE = /^studio_[0-9a-f]{8}_[0-9a-f]{4}_[0-9a-f]{4}_[0-9a-f]{4}_[0-9a-f]{12}$/i;

/** Per-client pool ceiling. Keeps total connections bounded across many gyms. */
const PER_CLIENT_CONNECTION_LIMIT = 3;

@Injectable()
export class TenantClientFactory implements OnModuleDestroy {
  private readonly logger = new Logger(TenantClientFactory.name);
  private readonly cache = new Map<string, TenantPrismaClient>();
  private readonly baseUrl: string;

  constructor(baseUrl: string = process.env.DATABASE_URL ?? '') {
    if (!baseUrl) throw new Error('TenantClientFactory: DATABASE_URL is required');
    this.baseUrl = baseUrl;
  }

  /**
   * Get (or lazily create) the cached client bound to a specific tenant schema.
   * Rejects any schema name that is not exactly `studio_<uuid>` — the only thing
   * standing between a typo/injection and a wrong-schema connection.
   */
  forSchema(schemaName: string): TenantPrismaClient {
    if (!TENANT_SCHEMA_RE.test(schemaName)) {
      throw new BadRequestException(`Invalid tenant schema: ${schemaName}`);
    }
    let client = this.cache.get(schemaName);
    if (!client) {
      client = new TenantPrismaClient({
        datasources: { db: { url: this.buildUrl(schemaName) } },
      });
      this.cache.set(schemaName, client);
      this.logger.log(`Created tenant client for ${schemaName} (cached: ${this.cache.size})`);
    }
    return client;
  }

  /** Append `?schema=` (and a bounded pool) without clobbering existing params. */
  private buildUrl(schemaName: string): string {
    const sep = this.baseUrl.includes('?') ? '&' : '?';
    return `${this.baseUrl}${sep}schema=${schemaName}&connection_limit=${PER_CLIENT_CONNECTION_LIMIT}`;
  }

  async onModuleDestroy(): Promise<void> {
    await Promise.all([...this.cache.values()].map((c) => c.$disconnect().catch(() => undefined)));
    this.cache.clear();
  }
}
