// Phase-2 schema split: partitions schema.prisma into a registry (public) schema
// and a tenant schema, each a self-contained Prisma schema with its own client.
// Verified preconditions: 0 cross-schema relations, 0 enums.
const fs = require('fs');
const dir = 'e:/Projects/musclex/backend/prisma';
const src = fs.readFileSync(dir + '/schema.prisma', 'utf8');

const blocks = [...src.matchAll(/model\s+(\w+)\s*\{([\s\S]*?)\n\}/g)];
const pub = [], ten = [];
for (const [, name, body] of blocks) {
  const schema = (body.match(/@@schema\("([^"]+)"\)/) || [])[1];
  const cleaned = body.split('\n').filter((l) => !/@@schema\(/.test(l)).join('\n');
  const block = `model ${name} {${cleaned}\n}\n`;
  if (schema === 'public') pub.push(block);
  else ten.push(block);
}

const header = (output) => `// AUTO-GENERATED by scripts/_phase2_split.js — do not hand-edit yet.
generator client {
  provider      = "prisma-client-js"
  output        = "../node_modules/.prisma/${output}"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

fs.writeFileSync(dir + '/schema.public.prisma', header('client-public') + pub.join('\n'));
fs.writeFileSync(dir + '/schema.tenant.prisma', header('client-tenant') + ten.join('\n'));
console.log(`Wrote schema.public.prisma (${pub.length} models) + schema.tenant.prisma (${ten.length} models)`);
