#!/usr/bin/env node
/**
 * Phase-2 schema split: partitions `prisma/schema.prisma` into a registry
 * (public) schema and a tenant schema, each a self-contained Prisma schema
 * with its own generated client.
 *
 * Verified preconditions when this was written: 0 cross-schema relations,
 * 0 enums. Both are re-checked at runtime now (see below) rather than assumed,
 * because a schema that has since grown either one would be split into two
 * files that generate but do not work.
 *
 * Usage:
 *   node scripts/_phase2_split.js            # rewrite both split schemas
 *   node scripts/_phase2_split.js --check    # verify they match; exit 1 if not
 *
 * `--check` is the useful one in CI: it turns "someone hand-edited a generated
 * file and the two clients drifted" from a runtime mystery into a failed build.
 */
const fs = require('fs');
const path = require('path');

// Resolved from THIS file's location. The previous version hardcoded
// 'e:/Projects/musclex/backend/prisma', so the script could not run on any
// machine but the one it was written on — which is why both split schemas
// ended up hand-edited despite their "do not hand-edit" header.
const dir = path.resolve(__dirname, '..', 'prisma');
const SRC = path.join(dir, 'schema.prisma');

const checkOnly = process.argv.includes('--check');

if (!fs.existsSync(SRC)) {
  console.error(`Cannot find ${SRC}`);
  process.exit(1);
}
const src = fs.readFileSync(SRC, 'utf8');

// ── Preconditions ───────────────────────────────────────────────────────────
// The split is only sound while these hold. Both are cheap to check and
// expensive to discover later.
const enums = [...src.matchAll(/^enum\s+(\w+)\s*\{/gm)].map((m) => m[1]);
if (enums.length > 0) {
  console.error(
    `Refusing to split: schema.prisma now declares ${enums.length} enum(s) ` +
      `(${enums.join(', ')}). Enums are not partitioned by this script, so ` +
      `each half would reference a type it does not define.`,
  );
  process.exit(1);
}

// ── Partition ───────────────────────────────────────────────────────────────
const blocks = [...src.matchAll(/(?:^|\n)((?:\/\/\/[^\n]*\n)*)model\s+(\w+)\s*\{([\s\S]*?)\n\}/g)];
if (blocks.length === 0) {
  console.error('Refusing to split: no models matched in schema.prisma.');
  process.exit(1);
}

const schemaOf = new Map();
const pub = [];
const ten = [];

for (const [, docs, name, body] of blocks) {
  const schema = (body.match(/@@schema\("([^"]+)"\)/) || [])[1];
  schemaOf.set(name, schema);
  // `@@schema` is a multiSchema directive; each split file has a single
  // datasource schema, so carrying it over would fail validation.
  const cleaned = body
    .split('\n')
    .filter((l) => !/@@schema\(/.test(l))
    .join('\n');
  // Doc comments are part of the model's meaning — they are why a reader knows
  // a table is deliberately outside TENANT_MODELS. The previous version
  // dropped them.
  const block = `${docs}model ${name} {${cleaned}\n}\n`;
  (schema === 'public' ? pub : ten).push(block);
}

// Relations that cross the partition would generate a client whose `include`
// targets a model that does not exist in that client.
const crossings = [];
for (const [, , name, body] of blocks) {
  const mine = schemaOf.get(name) === 'public' ? 'public' : 'tenant';
  for (const line of body.split('\n')) {
    // A relation field: `field  Model` or `field  Model[]` or `Model?`, with @relation
    const m = line.match(/^\s*\w+\s+(\w+)(\[\]|\?)?\s/);
    if (!m) continue;
    const target = m[1];
    if (!schemaOf.has(target)) continue; // scalar or unknown type
    const theirs = schemaOf.get(target) === 'public' ? 'public' : 'tenant';
    if (theirs !== mine) crossings.push(`${name}.${m[0].trim()} -> ${target}`);
  }
}
if (crossings.length > 0) {
  console.error(
    `Refusing to split: ${crossings.length} relation(s) cross the public/tenant ` +
      `boundary:\n  ${crossings.join('\n  ')}`,
  );
  process.exit(1);
}

const header = (output) => `// AUTO-GENERATED by scripts/_phase2_split.js — do not hand-edit.
// Regenerate:  node scripts/_phase2_split.js
// Verify:      node scripts/_phase2_split.js --check
generator client {
  provider      = "prisma-client-js"
  output        = "../node_modules/.prisma/${output}"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

const targets = [
  { file: path.join(dir, 'schema.public.prisma'), body: header('client-public') + pub.join('\n') },
  { file: path.join(dir, 'schema.tenant.prisma'), body: header('client-tenant') + ten.join('\n') },
];

/*
 * `prisma format` realigns columns, and the committed split schemas are
 * formatted. A byte comparison would therefore report drift on every run and
 * teach everyone to ignore this check — which is how the files came to be
 * hand-edited in the first place. Compare what actually matters instead:
 * the models and fields, with runs of whitespace collapsed and the
 * regenerate/verify header lines dropped.
 */
function normalise(text) {
  return text
    .split('\n')
    .map((l) => l.replace(/\s+/g, ' ').trim())
    .filter((l) => l.length > 0 && !l.startsWith('//'))
    .join('\n');
}

if (checkOnly) {
  const stale = targets.filter(
    (t) =>
      !fs.existsSync(t.file) ||
      normalise(fs.readFileSync(t.file, 'utf8')) !== normalise(t.body),
  );
  if (stale.length > 0) {
    console.error(
      'Split schemas are out of date with schema.prisma:\n  ' +
        stale.map((t) => path.relative(dir, t.file)).join('\n  ') +
        '\nRun: node scripts/_phase2_split.js',
    );
    process.exit(1);
  }
  console.log(`Split schemas match schema.prisma (${pub.length} public + ${ten.length} tenant models).`);
  process.exit(0);
}

for (const t of targets) fs.writeFileSync(t.file, t.body);
console.log(
  `Wrote schema.public.prisma (${pub.length} models) + schema.tenant.prisma (${ten.length} models)`,
);
