/**
 * ────────────────────────────────────────────────────────────────
 * GENERATE THE BUNDLED EXERCISE CATALOGUE
 * ────────────────────────────────────────────────────────────────
 *
 *   npx ts-node scripts/generate-exercise-catalogue.ts
 *
 * Emits `src/plans/exercise-catalogue.data.ts` from the ExerciseGymGifsDB
 * metadata, applying exactly the same classification mapping as
 * `import-exercise-catalogue.ts` — the two must not drift, so the mapping
 * lives here and that script's copy is the historical one.
 *
 * WHY BAKED IN rather than read at runtime: the catalogue is seeded when a
 * studio is provisioned, and a deploy that ships only `backend/` has no
 * sibling dataset directory to read. A committed module is available wherever
 * the server runs.
 *
 * CLASSIFICATION ONLY — no media_url, no instructions. That dataset's own
 * README says the GIFs were "extraídos de Internet", that the author does not
 * hold their copyright and cannot grant rights over them, and the repo carries
 * no LICENSE. The instruction prose came from the same scrape. Exercise names
 * and their muscle/equipment classification are facts about movements, not
 * that author's creative work, which is why those columns and only those are
 * carried across.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const DATASET = join(__dirname, '../../ExerciseGymGifsDB-main/api/en/exercises.json');
const OUT = join(__dirname, '../src/plans/exercise-catalogue.data.ts');

interface SourceExercise {
  name: string;
  muscle: string;
  bodyPart: string;
  equipment: string;
  category: string;
  secondaryMuscles?: string[];
}

const MUSCLE_GROUP: Record<string, string> = {
  arms: 'arms', back: 'back', cardio: 'cardio', chest: 'chest',
  core: 'core', legs: 'legs', shoulders: 'shoulders',
};

function targetMuscle(e: SourceExercise): string {
  const n = e.name.toLowerCase();
  if (e.muscle === 'delts') {
    if (/\b(front|anterior)\b/.test(n)) return 'front_delt';
    if (/\b(rear|reverse|posterior|bent[- ]over)\b/.test(n)) return 'rear_delt';
    if (/\b(lateral|side)\b/.test(n)) return 'side_delt';
    return 'front_delt';
  }
  if (e.muscle === 'pectorals') {
    if (/\bincline\b/.test(n)) return 'upper_chest';
    if (/\bdecline\b/.test(n)) return 'lower_chest';
    return 'mid_chest';
  }
  if (e.muscle === 'spine') return 'spinal_erectors';
  if (e.muscle === 'upper-back') return 'traps';
  return e.muscle.replace(/-/g, '_');
}

const trackingType = (e: SourceExercise) =>
  e.category === 'cardio' || e.category === 'stretching' ? 'duration' : 'reps';

const raw = JSON.parse(readFileSync(DATASET, 'utf8'));
const source: SourceExercise[] = Array.isArray(raw) ? raw : raw.exercises;

const seen = new Set<string>();
const rows = source
  .filter((e) => MUSCLE_GROUP[e.bodyPart])
  // The dataset carries duplicate names; the catalogue is unique on
  // (gym_id, name), so collapse them here rather than letting the insert fail.
  .filter((e) => (seen.has(e.name) ? false : (seen.add(e.name), true)))
  .map((e) => ({
    name: e.name,
    muscle_group: MUSCLE_GROUP[e.bodyPart],
    target_muscle: targetMuscle(e),
    secondary_muscles: (e.secondaryMuscles ?? []).map((m) => m.replace(/-/g, '_')),
    equipment: e.equipment,
    tracking_type: trackingType(e),
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

const body = `/**
 * GENERATED by scripts/generate-exercise-catalogue.ts — do not hand-edit.
 *
 * The catalogue every new gym is seeded with. Classification only: no media
 * and no instruction prose, because the source dataset's media is scraped and
 * unlicensed. See the generator for the full reasoning.
 *
 * ${rows.length} exercises.
 */
export interface CatalogueExercise {
  name: string;
  muscle_group: string;
  target_muscle: string;
  secondary_muscles: string[];
  equipment: string;
  tracking_type: string;
}

export const EXERCISE_CATALOGUE: CatalogueExercise[] = ${JSON.stringify(rows, null, 2)};
`;

writeFileSync(OUT, body);
console.log(`wrote ${rows.length} exercises to src/plans/exercise-catalogue.data.ts`);
