/**
 * Shared email layout — every MuscleX transactional email is built on this.
 *
 * Brand: Geist monochrome (admin design system) — ink #171717 on white canvas,
 * matching `frontend/src/app/globals.css`. Single accent = ink (no blue/green),
 * which also fixes the three off-brand palettes the audit found.
 *
 * Constraints baked in:
 *  - Table-based + inline styles (email clients strip <style>/flex/grid).
 *  - max-width 480px, fluid → mobile responsive.
 *  - Preheader text for inbox preview.
 *  - prefers-color-scheme: dark support (graceful; ignored where unsupported).
 *  - Semantic-ish structure, descriptive CTA text, ≥4.5:1 contrast.
 *  - A plain-text alternative is generated by every template (see text helpers).
 */

const BRAND = {
  ink: '#171717',
  canvas: '#ffffff',
  canvasSoft: '#fafafa',
  hairline: '#ebebeb',
  bodyInk: '#4d4d4d',
  mute: '#888888',
  onInk: '#ffffff',
  error: '#ee0000',
  warning: '#ab570a',
};

/** Escape a value before interpolating into HTML. Prevents injection (audit S3). */
export function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export interface LayoutBlocks {
  /** Inbox-preview text (hidden in the body). */
  preheader: string;
  heading: string;
  /** Pre-escaped HTML paragraphs/rows for the body. Use the helpers below. */
  bodyHtml: string;
  cta?: { label: string; url: string };
  /** Small print under the CTA (already-escaped HTML). */
  footnoteHtml?: string;
}

/** A normal body paragraph. Escapes its text. */
export function p(text: string): string {
  return `<p style="margin:0 0 16px;font-size:14px;line-height:1.6;color:${BRAND.bodyInk};">${esc(text)}</p>`;
}

/** A body paragraph that may contain pre-built (already-escaped) inline HTML. */
export function pRaw(html: string): string {
  return `<p style="margin:0 0 16px;font-size:14px;line-height:1.6;color:${BRAND.bodyInk};">${html}</p>`;
}

/** A label: value detail row (both escaped). For security/billing emails. */
export function detailRow(label: string, value: string): string {
  return (
    `<tr>` +
    `<td style="padding:6px 0;font-size:13px;color:${BRAND.mute};width:40%;">${esc(label)}</td>` +
    `<td style="padding:6px 0;font-size:13px;color:${BRAND.ink};font-weight:600;">${esc(value)}</td>` +
    `</tr>`
  );
}

export function detailTable(rows: string[]): string {
  return (
    `<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" ` +
    `style="margin:0 0 16px;border-top:1px solid ${BRAND.hairline};border-bottom:1px solid ${BRAND.hairline};">` +
    rows.join('') +
    `</table>`
  );
}

/** Bold inline emphasis, escaped. */
export function strong(text: string): string {
  return `<strong style="color:${BRAND.ink};">${esc(text)}</strong>`;
}

/** Render the full branded HTML document. All inputs must already be escaped. */
export function renderLayout(blocks: LayoutBlocks): string {
  const cta = blocks.cta
    ? `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 24px;">
         <tr><td align="center" bgcolor="${BRAND.ink}" style="border-radius:8px;">
           <a href="${esc(blocks.cta.url)}" target="_blank"
              style="display:inline-block;padding:12px 32px;font-size:14px;font-weight:600;
                     color:${BRAND.onInk};text-decoration:none;border-radius:8px;">
             ${esc(blocks.cta.label)}
           </a>
         </td></tr>
       </table>`
    : '';

  const footnote = blocks.footnoteHtml
    ? `<p style="margin:16px 0 0;font-size:12px;line-height:1.5;color:${BRAND.mute};">${blocks.footnoteHtml}</p>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="color-scheme" content="light dark" />
  <meta name="supported-color-schemes" content="light dark" />
  <title>${esc(blocks.heading)}</title>
  <style>
    @media (prefers-color-scheme: dark) {
      .mx-canvas { background:#121212 !important; }
      .mx-card { background:#1c1c1c !important; }
      .mx-heading { color:#f5f5f5 !important; }
      .mx-body { color:#bdbdbd !important; }
    }
  </style>
</head>
<body class="mx-canvas" style="margin:0;padding:0;background:${BRAND.canvasSoft};">
  <span style="display:none;max-height:0;overflow:hidden;opacity:0;">${esc(blocks.preheader)}</span>
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:${BRAND.canvasSoft};">
    <tr><td align="center" style="padding:32px 16px;">
      <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="480"
             class="mx-card" style="max-width:480px;width:100%;background:${BRAND.canvas};border:1px solid ${BRAND.hairline};border-radius:12px;">
        <tr><td style="padding:32px 32px 8px;">
          <table role="presentation" cellpadding="0" cellspacing="0" border="0">
            <tr>
              <td style="background:${BRAND.ink};border-radius:8px;width:36px;height:36px;text-align:center;vertical-align:middle;">
                <span style="color:${BRAND.onInk};font-weight:700;font-size:18px;font-family:Arial,Helvetica,sans-serif;">M</span>
              </td>
              <td style="padding-left:10px;font-weight:700;font-size:16px;color:${BRAND.ink};font-family:Arial,Helvetica,sans-serif;">MuscleX</td>
            </tr>
          </table>
        </td></tr>
        <tr><td style="padding:16px 32px 32px;font-family:Arial,Helvetica,sans-serif;">
          <h1 class="mx-heading" style="margin:0 0 12px;font-size:22px;font-weight:700;color:${BRAND.ink};">${esc(blocks.heading)}</h1>
          <div class="mx-body">${blocks.bodyHtml}</div>
          ${cta}
          ${footnote}
        </td></tr>
        <tr><td style="padding:16px 32px 28px;border-top:1px solid ${BRAND.hairline};">
          <p style="margin:0;font-size:11px;line-height:1.5;color:${BRAND.mute};font-family:Arial,Helvetica,sans-serif;">
            MuscleX — the operating system for modern fitness studios.
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

/** Build a plain-text alternative from heading + lines + optional CTA url. */
export function renderText(heading: string, lines: string[], ctaUrl?: string): string {
  const parts = [heading, '', ...lines];
  if (ctaUrl) parts.push('', ctaUrl);
  parts.push('', '— MuscleX');
  return parts.join('\n');
}
