-- ============================================================
-- Migration: dashboard_action_states + dashboard_action_receipts
--
-- Stores per-tenant dismiss/snooze state for the Action Stack
-- and an audit log of every action taken from the dashboard.
-- Action IDs are deterministic strings generated by the rules
-- engine (e.g. "renewal_at_risk:<member_id>:<end_date>") so we
-- can re-derive them each request and look up persisted state.
--
-- Run: psql $DATABASE_URL -f migration.sql
-- ============================================================

-- 1. Action state (one row per (gym, action_id))
CREATE TABLE IF NOT EXISTS "studio_template"."dashboard_action_states" (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    gym_id              UUID NOT NULL,
    branch_id           UUID,
    action_id           TEXT NOT NULL,
    state               TEXT NOT NULL,                  -- 'dismissed' | 'snoozed'
    snoozed_until       TIMESTAMPTZ,                    -- non-null when state='snoozed'
    updated_by_user_id  UUID,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_action_state UNIQUE (gym_id, action_id),
    CONSTRAINT chk_state CHECK (state IN ('dismissed', 'snoozed'))
);

CREATE INDEX IF NOT EXISTS idx_action_states_gym_branch
    ON "studio_template"."dashboard_action_states" (gym_id, branch_id);
CREATE INDEX IF NOT EXISTS idx_action_states_snoozed_until
    ON "studio_template"."dashboard_action_states" (snoozed_until)
    WHERE state = 'snoozed';

-- 2. Receipts log (immutable history of every action taken)
CREATE TABLE IF NOT EXISTS "studio_template"."dashboard_action_receipts" (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    gym_id          UUID NOT NULL,
    branch_id       UUID,
    action_id       TEXT NOT NULL,
    action_kind     TEXT NOT NULL,                      -- e.g. 'renewal_at_risk'
    receipt_type    TEXT NOT NULL,                      -- 'resolved' | 'dismissed' | 'snoozed' | 'bulk_resolved'
    actor_user_id   UUID,
    actor_role      TEXT,
    payload         JSONB,                              -- arbitrary context
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_receipts_gym_created
    ON "studio_template"."dashboard_action_receipts" (gym_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_receipts_action_id
    ON "studio_template"."dashboard_action_receipts" (action_id);

-- 3. Apply to all existing tenant schemas
DO $$
DECLARE
    schema_name TEXT;
BEGIN
    FOR schema_name IN
        SELECT nspname FROM pg_namespace WHERE nspname LIKE 'studio_%' AND nspname != 'studio_template'
    LOOP
        EXECUTE format('
            CREATE TABLE IF NOT EXISTS %I.dashboard_action_states (
                id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                gym_id              UUID NOT NULL,
                branch_id           UUID,
                action_id           TEXT NOT NULL,
                state               TEXT NOT NULL,
                snoozed_until       TIMESTAMPTZ,
                updated_by_user_id  UUID,
                created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                CONSTRAINT uq_action_state_%I UNIQUE (gym_id, action_id),
                CONSTRAINT chk_state_%I CHECK (state IN (''dismissed'', ''snoozed''))
            );
            CREATE INDEX IF NOT EXISTS idx_action_states_gym_branch_%I
                ON %I.dashboard_action_states (gym_id, branch_id);
            CREATE INDEX IF NOT EXISTS idx_action_states_snoozed_%I
                ON %I.dashboard_action_states (snoozed_until)
                WHERE state = ''snoozed'';

            CREATE TABLE IF NOT EXISTS %I.dashboard_action_receipts (
                id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                gym_id          UUID NOT NULL,
                branch_id       UUID,
                action_id       TEXT NOT NULL,
                action_kind     TEXT NOT NULL,
                receipt_type    TEXT NOT NULL,
                actor_user_id   UUID,
                actor_role      TEXT,
                payload         JSONB,
                created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS idx_receipts_gym_created_%I
                ON %I.dashboard_action_receipts (gym_id, created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_receipts_action_id_%I
                ON %I.dashboard_action_receipts (action_id);
        ',
        schema_name, schema_name, schema_name,
        schema_name, schema_name, schema_name, schema_name,
        schema_name, schema_name, schema_name, schema_name, schema_name);
    END LOOP;
END $$;
