export type BranchScopeTier = 'STRICT' | 'SHARED_OR_BRANCHED' | 'GYM_WIDE';

export const BRANCH_SCOPE: Record<string, BranchScopeTier> = {
  // ── STRICT: branch_id NOT NULL ─────────────────────────────────
  Member: 'STRICT',
  CheckIn: 'STRICT',
  Payment: 'STRICT',
  ClassSession: 'STRICT',
  ClassBooking: 'STRICT',
  ClassWaitlist: 'STRICT',
  ClassAttendance: 'STRICT',
  TrainerAssignment: 'STRICT',
  StudioRoom: 'STRICT',
  ClassEnrollment: 'STRICT',
  FinancialTransaction: 'STRICT',
  StaffShift: 'STRICT',
  StaffAttendance: 'STRICT',
  TrainerSession: 'STRICT',
  TrainerClient: 'STRICT',
  PosSale: 'STRICT',
  Refund: 'STRICT',
  PaymentRetryLog: 'STRICT',
  MemberInvoice: 'STRICT',
  InvoiceItem: 'STRICT',
  ServiceBooking: 'STRICT',
  Review: 'STRICT',

  // ── SHARED_OR_BRANCHED: branch_id nullable ─────────────────────
  MembershipPlan: 'SHARED_OR_BRANCHED',
  ClassTemplate: 'SHARED_OR_BRANCHED',
  Staff: 'SHARED_OR_BRANCHED',
  Campaign: 'SHARED_OR_BRANCHED',
  Lead: 'SHARED_OR_BRANCHED',
  NotificationLog: 'SHARED_OR_BRANCHED',
  Expense: 'SHARED_OR_BRANCHED',
  DashboardMetrics: 'SHARED_OR_BRANCHED',
  DomainEvent: 'SHARED_OR_BRANCHED',
  ClassRecurringRule: 'SHARED_OR_BRANCHED',
  MemberMembership: 'SHARED_OR_BRANCHED',
  Discount: 'SHARED_OR_BRANCHED',
  BranchFranchise: 'SHARED_OR_BRANCHED',
  LeadActivity: 'SHARED_OR_BRANCHED',
  CampaignAudience: 'SHARED_OR_BRANCHED',
  ProductCategory: 'SHARED_OR_BRANCHED',
  Product: 'SHARED_OR_BRANCHED',
  Inventory: 'SHARED_OR_BRANCHED',
  InventoryTransaction: 'SHARED_OR_BRANCHED',
  Supplier: 'SHARED_OR_BRANCHED',
  PurchaseOrder: 'SHARED_OR_BRANCHED',
  PurchaseOrderItem: 'SHARED_OR_BRANCHED',
  PosSaleItem: 'SHARED_OR_BRANCHED',
  ProductReturn: 'SHARED_OR_BRANCHED',
  Webhook: 'SHARED_OR_BRANCHED',
  WebhookDelivery: 'SHARED_OR_BRANCHED',
  Integration: 'SHARED_OR_BRANCHED',

  // ── GYM_WIDE: no branch_id column ─────────────────────────────
  Organization: 'GYM_WIDE',
  OrganizationSettings: 'GYM_WIDE',
  Region: 'GYM_WIDE',
  Branch: 'GYM_WIDE',
  BranchSettings: 'GYM_WIDE',
  FranchiseOwner: 'GYM_WIDE',
  MemberProfile: 'GYM_WIDE',
  MemberBodyStats: 'GYM_WIDE',
  MemberProgressPhoto: 'GYM_WIDE',
  MemberNote: 'GYM_WIDE',
  MemberTag: 'GYM_WIDE',
  MemberTagAssignment: 'GYM_WIDE',
  MemberDocument: 'GYM_WIDE',
  MemberReferral: 'GYM_WIDE',
  MembershipFreeze: 'GYM_WIDE',
  FamilyMembership: 'GYM_WIDE',
  FamilyMember: 'GYM_WIDE',
  CorporateAccount: 'GYM_WIDE',
  CorporateMember: 'GYM_WIDE',
  GlobalAccessPass: 'GYM_WIDE',
  Role: 'GYM_WIDE',
  RolePermission: 'GYM_WIDE',
  StaffProfile: 'GYM_WIDE',
  StaffAvailability: 'GYM_WIDE',
  PayrollConfig: 'GYM_WIDE',
  TrainerRevenue: 'GYM_WIDE',
  LeaveRequest: 'GYM_WIDE',
  PayrollRecord: 'GYM_WIDE',
  TrainerPerformanceRecord: 'GYM_WIDE',
  AuditLog: 'GYM_WIDE',
  MessageTemplate: 'GYM_WIDE',
  AutomationWorkflow: 'GYM_WIDE',
  WorkflowAction: 'GYM_WIDE',
  ReferralProgram: 'GYM_WIDE',
  PushNotification: 'GYM_WIDE',
  AiConversation: 'GYM_WIDE',
  SsoProvider: 'GYM_WIDE',
  ApiKey: 'GYM_WIDE',
  PaymentGatewayConfig: 'GYM_WIDE',
  TaxRate: 'GYM_WIDE',
  DailyGymMetrics: 'GYM_WIDE',
  MembershipAnalytics: 'GYM_WIDE',
  RevenueAnalytics: 'GYM_WIDE',
  ClassAnalytics: 'GYM_WIDE',
  MemberBehaviorAnalytics: 'GYM_WIDE',
  TrainerAnalytics: 'GYM_WIDE',
  CampaignAnalyticsRecord: 'GYM_WIDE',
  FeatureFlag: 'GYM_WIDE',
  WhiteLabelConfig: 'GYM_WIDE',
  SystemNotification: 'GYM_WIDE',
  ConsentLog: 'GYM_WIDE',
  DataRequest: 'GYM_WIDE',
  BookingTransition: 'GYM_WIDE',
  ProviderAvailabilitySlot: 'GYM_WIDE',
  BookingDispute: 'GYM_WIDE',
  ServiceProvider: 'GYM_WIDE',
  ServiceCatalog: 'GYM_WIDE',
  Chat: 'GYM_WIDE',
  ChatMessage: 'GYM_WIDE',
  Notification: 'GYM_WIDE',
  ProviderSubscription: 'GYM_WIDE',
  StaffPermissionOverride: 'GYM_WIDE',
  Class: 'GYM_WIDE',
};

/** Returns the branch-scope tier for a Prisma model. Defaults to GYM_WIDE for unknown models. */
export function getBranchScopeTier(model: string): BranchScopeTier {
  return BRANCH_SCOPE[model] ?? 'GYM_WIDE';
}
