/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an OTP for a phone number
         * @description Looks up the phone in the public-schema member directory. If found, triggers Supabase phone OTP. Always returns 200 (do not reveal whether a phone is a member — prevents enumeration).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example +919876543210 */
                        phone: string;
                    };
                };
            };
            responses: {
                /** @description OTP dispatched if the phone maps to a member */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OtpRequestResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a verified Supabase OTP token for a member session
         * @description Verifies the Supabase access token, resolves the member via the public directory, and issues the app's member access + refresh tokens. If the phone maps to multiple gyms, returns `tenantChoices` and no tokens until a tenant is selected.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        supabaseToken: string;
                        /** @description Required only when resolving a multi-gym member */
                        tenantId?: string;
                    };
                };
            };
            responses: {
                /** @description Session issued (or tenant choice required) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResult"];
                    };
                };
                403: components["responses"]["NotAMember"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description New token pair */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current member profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["MemberProfile"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Composite dashboard payload (one call powers the Home screen) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["HomeDashboard"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gym/occupancy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live gym occupancy (polling fallback for the realtime channel) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Occupancy"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gym/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This gym's branches with coordinates (powers the in-app gym/branch finder)
         * @description Returns the branches of the member's current gym (tenant), each with its address and lat/lng when set, so the app can map them and let the member find the nearest location. Scoped to the member's tenant — never returns other gyms' branches.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["GymLocations"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a check-in (idempotent; offline-queued writes are safe) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        method: "qr" | "manual";
                        /** @description QR/scan token when method=qr */
                        token?: string;
                        /**
                         * Format: date-time
                         * @description Client timestamp (server is authoritative on accept/reject)
                         */
                        occurredAt?: string;
                    };
                };
            };
            responses: {
                /** @description Checked in (or already recorded for this idempotency key) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["CheckInResult"];
                        };
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current membership, plan, expiry, recent invoices */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Membership"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/membership/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a renewal/upgrade — returns a Razorpay order to open in checkout
         * @description Creates a Razorpay order via the existing per-tenant Razorpay flow. Payment is confirmed server-side by webhook; the app should refresh /membership (or await a push) rather than trusting the client result.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        planId: string;
                    };
                };
            };
            responses: {
                /** @description Razorpay order created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["RazorpayOrder"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workouts/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today's assigned workout (or null if none assigned) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Workout"] | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workouts/{workoutId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log completed sets for a workout (idempotent, offline-safe) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    workoutId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        sets: components["schemas"]["SetLog"][];
                    };
                };
            };
            responses: {
                /** @description Logged */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["WorkoutLogResult"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Upcoming classes at the member's branch (with this member's booking state)
         * @description Returns future, non-cancelled classes scheduled at the member's own branch, soonest first. `seatsLeft` counts only ENROLLED bookings. `booked`/`bookingStatus` reflect THIS member only — other members' identities are never returned. Scoped to the member's tenant + branch.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ClassList"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{classId}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Book (enroll) the current member into a class; waitlists if full
         * @description Idempotent. Reuses the same capacity/waitlist/duplicate rules as the front-desk enrollment path. If the class is full the member is placed on the waitlist and `status=waitlisted` with a `waitlistPosition`.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    classId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booked (or waitlisted), or replayed for this idempotency key */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ClassBookingResult"];
                        };
                    };
                };
                404: components["responses"]["NotAMember"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{classId}/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel the current member's booking for a class
         * @description Cancels this member's enrolled/waitlisted booking. If an enrolled seat is freed, the next waitlisted member is auto-promoted (same rule as the front-desk path).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ClassCancelResult"];
                        };
                    };
                };
                404: components["responses"]["NotAMember"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Body metrics history + summary for graphs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Progress"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log a body metric (weight, measurements) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BodyMetricInput"];
                };
            };
            responses: {
                /** @description Logged */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["BodyMetric"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/photos/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a signed URL to upload a progress photo directly to object storage
         * @description Keeps media out of the API. App PUTs the file to the signed URL, then confirms via POST /progress/photos. Photos are private by default.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example image/jpeg */
                        contentType: string;
                    };
                };
            };
            responses: {
                /** @description Signed upload URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["UploadTarget"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an uploaded progress photo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        photoId: string;
                        /** Format: date-time */
                        takenAt: string;
                    };
                };
            };
            responses: {
                /** @description Confirmed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/device-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a device push token (idempotent upsert) with category prefs */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        /** @enum {string} */
                        platform: "ios" | "android";
                        /** @description Per-category opt-in flags (true = send). Server honours these. */
                        prefs?: {
                            [key: string]: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description Registered */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Unregister a device push token (on disable / sign-out) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Unregistered */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today's nutrition — goal, running totals, water, and logged meals
         * @description The member's nutrition for the current day (their local day boundary on the server): per-member daily goal (created with defaults on first read), macro totals summed from logged meals, total water, and the meals themselves. Scoped to the member's tenant + member_id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["NutritionDay"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the gym's food catalog */
        get: {
            parameters: {
                query?: {
                    /** @description Case-insensitive name/brand prefix match. Empty = recent foods. */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["FoodSearch"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log a meal with its items (idempotent, offline-safe) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MealLogInput"];
                };
            };
            responses: {
                /** @description Logged */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["MealLogResult"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition/water": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log water intake (idempotent, offline-safe) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WaterLogInput"];
                };
            };
            responses: {
                /** @description Logged */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["WaterLogResult"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse / search the gym's exercise library
         * @description The gym's active exercises (the same catalog trainers build plans from), optionally filtered by name and muscle group. Scoped to the member's tenant.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Case-insensitive name match. */
                    q?: string;
                    /** @description Filter by muscle group (chest, back, legs, …). */
                    muscle?: string;
                    /** @description When true, returns only the member's favorited exercises. */
                    favorites?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ExerciseList"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One exercise's detail (instructions + media) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ExerciseDetail"];
                        };
                    };
                };
                404: components["responses"]["NotAMember"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark an exercise as a favorite (idempotent) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Favorited */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["FavoriteResult"];
                        };
                    };
                };
                404: components["responses"]["NotAMember"];
            };
        };
        post?: never;
        /** Remove an exercise from favorites (idempotent) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unfavorited */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["FavoriteResult"];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainer-chat/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The member's trainer conversations (one per assigned trainer)
         * @description One thread per active trainer assignment (TrainerClient), with the last message and the member's unread count. Scoped to the member's tenant.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ChatThreadList"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainer-chat/threads/{trainerId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Messages with a trainer (marks the trainer's messages read) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trainerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ChatMessageList"];
                        };
                    };
                };
                404: components["responses"]["NotAMember"];
            };
        };
        put?: never;
        /** Send a message to a trainer (idempotent, offline-safe) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    trainerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageInput"];
                };
            };
            responses: {
                /** @description Sent */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ChatMessage"];
                        };
                    };
                };
                404: components["responses"]["NotAMember"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gym attendance leaderboard (real check-ins over a period)
         * @description Ranks the member's gym by check-ins over the last `period` days. Returns first names only (no PII), the current member flagged with `isMe`, plus the member's own rank/value. Scoped to the member's tenant.
         */
        get: {
            parameters: {
                query?: {
                    period?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Leaderboard"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active gym challenges with the member's join state + real progress */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ChallengeList"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/challenges/{challengeId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a challenge (idempotent) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    challengeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Joined */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["ChallengeJoinResult"];
                        };
                    };
                };
                404: components["responses"]["NotAMember"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/badges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The member's badges (earned/locked, computed from real activity) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["BadgeList"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nutrition/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the member's daily nutrition goal (upsert) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NutritionGoalInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["NutritionGoal"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            data: Record<string, never>;
            meta: components["schemas"]["Meta"];
        };
        ErrorEnvelope: {
            error: {
                /** @example MEMBERSHIP_EXPIRED */
                code: string;
                message: string;
                /** @default false */
                retryable: boolean;
            };
        };
        Meta: {
            /** @example gym_017 */
            tenantId?: string;
            /** Format: date-time */
            serverTime?: string;
            /** @description Seconds the client may cache */
            cacheTtl?: number;
        };
        OtpRequestResult: {
            /** @example true */
            dispatched?: boolean;
            /**
             * @example sms
             * @enum {string}
             */
            channel?: "sms" | "whatsapp";
        };
        SessionResult: {
            tokens?: components["schemas"]["TokenPair"] | null;
            /** @description Present only when the phone maps to multiple gyms */
            tenantChoices?: {
                tenantId?: string;
                gymName?: string;
            }[];
        };
        TokenPair: {
            accessToken: string;
            refreshToken: string;
            /** @example 900 */
            expiresIn: number;
        };
        MemberProfile: {
            id?: string;
            name?: string;
            phone?: string;
            gymName?: string;
            /** @enum {string} */
            goal?: "lose_fat" | "build_muscle" | "general_fitness";
            /** @enum {string} */
            experienceLevel?: "beginner" | "intermediate" | "advanced";
            avatarUrl?: string | null;
        };
        HomeDashboard: {
            /** @example Good evening, Sneha */
            greeting?: string;
            membership?: {
                /** @enum {string} */
                status?: "active" | "expiring" | "expired" | "frozen";
                /** Format: date */
                expiresOn?: string;
                daysLeft?: number;
            };
            streak?: {
                days?: number;
            };
            /** @description Today's ritual status — which streak-qualifying actions the member has already done today (check-in, workout log, meal log), and whether an active streak is still at risk (no qualifying action logged yet today). */
            today?: {
                checkedIn?: boolean;
                workoutLogged?: boolean;
                mealLogged?: boolean;
                streakAtRisk?: boolean;
            };
            todayWorkout?: components["schemas"]["WorkoutSummary"] | null;
            nextClass?: components["schemas"]["ClassSummary"] | null;
            occupancy?: components["schemas"]["Occupancy"];
            /** @description Today's calories eaten vs goal and water vs goal (V2.1). */
            nutrition?: {
                kcal?: number;
                kcalGoal?: number;
                waterMl?: number;
                waterGoal?: number;
            };
        };
        Occupancy: {
            current?: number;
            capacity?: number;
            /** @enum {string} */
            level?: "low" | "moderate" | "high" | "full";
            /** Format: date-time */
            updatedAt?: string;
        };
        GymLocation: {
            id?: string;
            name?: string;
            address?: string | null;
            city?: string | null;
            /** @description Decimal degrees (WGS84) */
            latitude?: number | null;
            longitude?: number | null;
            phone?: string | null;
            /** @enum {string} */
            status?: "active" | "inactive" | "temporarily_closed" | "coming_soon" | "provisioning";
        };
        GymLocations: {
            branches?: components["schemas"]["GymLocation"][];
        };
        CheckInResult: {
            checkInId?: string;
            /** Format: date-time */
            recordedAt?: string;
            /** @description true if idempotent replay */
            alreadyRecorded?: boolean;
            streakDays?: number;
        };
        Membership: {
            /** @enum {string} */
            status?: "active" | "expiring" | "expired" | "frozen";
            plan?: {
                id?: string;
                name?: string;
                price?: number;
                /** @example INR */
                currency?: string;
            };
            /** Format: date */
            startedOn?: string;
            /** Format: date */
            expiresOn?: string;
            autoRenew?: boolean;
            invoices?: {
                id?: string;
                amount?: number;
                currency?: string;
                /** Format: date-time */
                paidOn?: string | null;
                /** @enum {string} */
                status?: "paid" | "pending" | "failed";
            }[];
        };
        RazorpayOrder: {
            orderId?: string;
            /** @description In paise */
            amount?: number;
            /** @example INR */
            currency?: string;
            razorpayKeyId?: string;
            receipt?: string;
        };
        WorkoutSummary: {
            id?: string;
            title?: string;
            assignedBy?: string | null;
            exerciseCount?: number;
        };
        Workout: {
            id?: string;
            title?: string;
            assignedBy?: string | null;
            exercises?: {
                id?: string;
                name?: string;
                targetSets?: number;
                targetReps?: number;
                mediaUrl?: string | null;
                lastLog?: components["schemas"]["SetLog"];
            }[];
        };
        SetLog: {
            exerciseId?: string;
            setNumber?: number;
            reps?: number;
            weight?: number;
            /**
             * @default kg
             * @enum {string}
             */
            unit: "kg" | "lb";
        };
        WorkoutLogResult: {
            logId?: string;
            newPersonalRecords?: {
                exerciseId?: string;
                weight?: number;
            }[];
        };
        ClassSummary: {
            id?: string;
            title?: string;
            /** Format: date-time */
            startsAt?: string;
            seatsLeft?: number;
        };
        ClassListItem: {
            id?: string;
            title?: string;
            category?: string;
            /** Format: date-time */
            startsAt?: string;
            durationMinutes?: number;
            room?: string | null;
            trainerName?: string | null;
            capacity?: number;
            seatsLeft?: number;
            /** @description true if THIS member has an active booking */
            booked?: boolean;
            /** @enum {string|null} */
            bookingStatus?: "enrolled" | "waitlisted" | null;
            waitlistPosition?: number | null;
        };
        ClassList: {
            classes?: components["schemas"]["ClassListItem"][];
        };
        ClassBookingResult: {
            classId?: string;
            /** @enum {string} */
            status?: "enrolled" | "waitlisted";
            waitlistPosition?: number | null;
            seatsLeft?: number;
            message?: string;
        };
        ClassCancelResult: {
            cancelled?: boolean;
            /** @description Name of the waitlisted member auto-promoted into the freed seat, if any */
            promotedMemberName?: string | null;
        };
        Progress: {
            latest?: {
                weightKg?: number | null;
                bmi?: number | null;
                bodyFatPct?: number | null;
            };
            series?: components["schemas"]["BodyMetric"][];
            photos?: {
                id?: string;
                /** @description Signed */
                url?: string;
                /** Format: date-time */
                takenAt?: string;
            }[];
        };
        BodyMetricInput: {
            weightKg?: number;
            waistCm?: number;
            /** Format: date-time */
            recordedAt?: string;
        };
        BodyMetric: {
            id?: string;
            weightKg?: number | null;
            bmi?: number | null;
            waistCm?: number | null;
            /** Format: date-time */
            recordedAt?: string;
        };
        UploadTarget: {
            photoId?: string;
            /** @description Signed PUT URL */
            uploadUrl?: string;
        };
        NutritionTotals: {
            kcal?: number;
            proteinG?: number;
            carbsG?: number;
            fatG?: number;
        };
        /** @description Per-member daily targets. */
        NutritionGoal: {
            kcal?: number;
            proteinG?: number;
            carbsG?: number;
            fatG?: number;
            waterMl?: number;
        };
        NutritionGoalInput: {
            kcal?: number;
            proteinG?: number;
            carbsG?: number;
            fatG?: number;
            waterMl?: number;
        };
        FoodItem: {
            id?: string;
            name?: string;
            brand?: string | null;
            barcode?: string | null;
            servingSize?: number;
            servingUnit?: string;
            kcal?: number;
            proteinG?: number;
            carbsG?: number;
            fatG?: number;
            /** @enum {string} */
            source?: "custom" | "catalog" | "barcode";
        };
        FoodSearch: {
            foods?: components["schemas"]["FoodItem"][];
        };
        NutritionMealItem: {
            id?: string;
            foodItemId?: string | null;
            name?: string;
            quantity?: number;
            unit?: string;
            kcal?: number;
            proteinG?: number;
            carbsG?: number;
            fatG?: number;
        };
        NutritionMeal: {
            id?: string;
            /** @enum {string} */
            mealType?: "breakfast" | "lunch" | "dinner" | "snack";
            /** Format: date-time */
            loggedAt?: string;
            notes?: string | null;
            totals?: components["schemas"]["NutritionTotals"];
            items?: components["schemas"]["NutritionMealItem"][];
        };
        NutritionDay: {
            /** Format: date */
            date?: string;
            goal?: components["schemas"]["NutritionGoal"];
            totals?: components["schemas"]["NutritionTotals"];
            waterMl?: number;
            meals?: components["schemas"]["NutritionMeal"][];
        };
        MealLogItemInput: {
            foodItemId?: string | null;
            name: string;
            quantity?: number;
            unit?: string;
            kcal?: number;
            proteinG?: number;
            carbsG?: number;
            fatG?: number;
        };
        MealLogInput: {
            /** @enum {string} */
            mealType: "breakfast" | "lunch" | "dinner" | "snack";
            /** Format: date-time */
            loggedAt?: string;
            notes?: string;
            items: components["schemas"]["MealLogItemInput"][];
        };
        MealLogResult: {
            mealId?: string;
        };
        WaterLogInput: {
            amountMl: number;
            /** Format: date-time */
            loggedAt?: string;
        };
        WaterLogResult: {
            waterId?: string;
            totalMl?: number;
        };
        ExerciseListItem: {
            id?: string;
            name?: string;
            muscleGroup?: string | null;
            equipment?: string | null;
            mediaUrl?: string | null;
            hasInstructions?: boolean;
            favorited?: boolean;
        };
        ExerciseList: {
            exercises?: components["schemas"]["ExerciseListItem"][];
        };
        ExerciseDetail: {
            id?: string;
            name?: string;
            muscleGroup?: string | null;
            equipment?: string | null;
            mediaUrl?: string | null;
            instructions?: string | null;
            favorited?: boolean;
        };
        FavoriteResult: {
            favorited?: boolean;
        };
        ChatThread: {
            trainerId?: string;
            trainerName?: string;
            trainerAvatarUrl?: string | null;
            lastMessage?: string | null;
            /** Format: date-time */
            lastMessageAt?: string | null;
            unreadCount?: number;
        };
        ChatThreadList: {
            threads?: components["schemas"]["ChatThread"][];
        };
        ChatMessage: {
            id?: string;
            /** @enum {string} */
            sender?: "member" | "trainer";
            body?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ChatMessageList: {
            trainerId?: string;
            trainerName?: string;
            messages?: components["schemas"]["ChatMessage"][];
        };
        SendMessageInput: {
            body: string;
        };
        LeaderboardEntry: {
            rank?: number;
            name?: string;
            value?: number;
            isMe?: boolean;
        };
        Leaderboard: {
            /** @example checkins */
            metric?: string;
            periodDays?: number;
            entries?: components["schemas"]["LeaderboardEntry"][];
            myRank?: number | null;
            myValue?: number;
        };
        ChallengeItem: {
            id?: string;
            title?: string;
            description?: string | null;
            /** @enum {string} */
            metric?: "checkins" | "workouts";
            goal?: number;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            joined?: boolean;
            progress?: number;
            completed?: boolean;
            participantCount?: number;
        };
        ChallengeList: {
            challenges?: components["schemas"]["ChallengeItem"][];
        };
        ChallengeJoinResult: {
            joined?: boolean;
            progress?: number;
        };
        Badge: {
            key?: string;
            label?: string;
            description?: string;
            earned?: boolean;
        };
        BadgeList: {
            badges?: components["schemas"]["Badge"][];
            earnedCount?: number;
            expiresIn?: number;
        };
    };
    responses: {
        /** @description Phone is not linked to any gym membership */
        NotAMember: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rejected (e.g., duplicate / stale / capacity) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Client-generated key. Server dedupes retries (offline outbox). */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
