/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an OTP for a phone number
         * @description Looks up the phone in the public-schema member directory. If found, triggers Supabase phone OTP. Always returns 200 (do not reveal whether a phone is a member — prevents enumeration).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example +919876543210 */
                        phone: string;
                    };
                };
            };
            responses: {
                /** @description OTP dispatched if the phone maps to a member */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OtpRequestResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a verified Supabase OTP token for a member session
         * @description Verifies the Supabase access token, resolves the member via the public directory, and issues the app's member access + refresh tokens. If the phone maps to multiple gyms, returns `tenantChoices` and no tokens until a tenant is selected.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        supabaseToken: string;
                        /** @description Required only when resolving a multi-gym member */
                        tenantId?: string;
                    };
                };
            };
            responses: {
                /** @description Session issued (or tenant choice required) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResult"];
                    };
                };
                403: components["responses"]["NotAMember"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description New token pair */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current member profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["MemberProfile"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Composite dashboard payload (one call powers the Home screen) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["HomeDashboard"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gym/occupancy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live gym occupancy (polling fallback for the realtime channel) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Occupancy"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a check-in (idempotent; offline-queued writes are safe) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        method: "qr" | "manual";
                        /** @description QR/scan token when method=qr */
                        token?: string;
                        /**
                         * Format: date-time
                         * @description Client timestamp (server is authoritative on accept/reject)
                         */
                        occurredAt?: string;
                    };
                };
            };
            responses: {
                /** @description Checked in (or already recorded for this idempotency key) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["CheckInResult"];
                        };
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current membership, plan, expiry, recent invoices */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Membership"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/membership/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a renewal/upgrade — returns a Razorpay order to open in checkout
         * @description Creates a Razorpay order via the existing per-tenant Razorpay flow. Payment is confirmed server-side by webhook; the app should refresh /membership (or await a push) rather than trusting the client result.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        planId: string;
                    };
                };
            };
            responses: {
                /** @description Razorpay order created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["RazorpayOrder"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workouts/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today's assigned workout (or null if none assigned) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Workout"] | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workouts/{workoutId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log completed sets for a workout (idempotent, offline-safe) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    workoutId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        sets: components["schemas"]["SetLog"][];
                    };
                };
            };
            responses: {
                /** @description Logged */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["WorkoutLogResult"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Body metrics history + summary for graphs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["Progress"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log a body metric (weight, measurements) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Server dedupes retries (offline outbox). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BodyMetricInput"];
                };
            };
            responses: {
                /** @description Logged */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["BodyMetric"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/photos/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a signed URL to upload a progress photo directly to object storage
         * @description Keeps media out of the API. App PUTs the file to the signed URL, then confirms via POST /progress/photos. Photos are private by default.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example image/jpeg */
                        contentType: string;
                    };
                };
            };
            responses: {
                /** @description Signed upload URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["UploadTarget"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an uploaded progress photo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        photoId: string;
                        /** Format: date-time */
                        takenAt: string;
                    };
                };
            };
            responses: {
                /** @description Confirmed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/device-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an FCM device token for push */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        /** @enum {string} */
                        platform: "ios" | "android";
                    };
                };
            };
            responses: {
                /** @description Registered */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            data: Record<string, never>;
            meta: components["schemas"]["Meta"];
        };
        ErrorEnvelope: {
            error: {
                /** @example MEMBERSHIP_EXPIRED */
                code: string;
                message: string;
                /** @default false */
                retryable: boolean;
            };
        };
        Meta: {
            /** @example gym_017 */
            tenantId?: string;
            /** Format: date-time */
            serverTime?: string;
            /** @description Seconds the client may cache */
            cacheTtl?: number;
        };
        OtpRequestResult: {
            /** @example true */
            dispatched?: boolean;
            /**
             * @example sms
             * @enum {string}
             */
            channel?: "sms" | "whatsapp";
        };
        SessionResult: {
            tokens?: components["schemas"]["TokenPair"] | null;
            /** @description Present only when the phone maps to multiple gyms */
            tenantChoices?: {
                tenantId?: string;
                gymName?: string;
            }[];
        };
        TokenPair: {
            accessToken: string;
            refreshToken: string;
            /** @example 900 */
            expiresIn: number;
        };
        MemberProfile: {
            id?: string;
            name?: string;
            phone?: string;
            gymName?: string;
            /** @enum {string} */
            goal?: "lose_fat" | "build_muscle" | "general_fitness";
            /** @enum {string} */
            experienceLevel?: "beginner" | "intermediate" | "advanced";
            avatarUrl?: string | null;
        };
        HomeDashboard: {
            /** @example Good evening, Sneha */
            greeting?: string;
            membership?: {
                /** @enum {string} */
                status?: "active" | "expiring" | "expired" | "frozen";
                /** Format: date */
                expiresOn?: string;
                daysLeft?: number;
            };
            streak?: {
                days?: number;
            };
            todayWorkout?: components["schemas"]["WorkoutSummary"] | null;
            nextClass?: components["schemas"]["ClassSummary"] | null;
            occupancy?: components["schemas"]["Occupancy"];
        };
        Occupancy: {
            current?: number;
            capacity?: number;
            /** @enum {string} */
            level?: "low" | "moderate" | "high" | "full";
            /** Format: date-time */
            updatedAt?: string;
        };
        CheckInResult: {
            checkInId?: string;
            /** Format: date-time */
            recordedAt?: string;
            /** @description true if idempotent replay */
            alreadyRecorded?: boolean;
            streakDays?: number;
        };
        Membership: {
            /** @enum {string} */
            status?: "active" | "expiring" | "expired" | "frozen";
            plan?: {
                id?: string;
                name?: string;
                price?: number;
                /** @example INR */
                currency?: string;
            };
            /** Format: date */
            startedOn?: string;
            /** Format: date */
            expiresOn?: string;
            autoRenew?: boolean;
            invoices?: {
                id?: string;
                amount?: number;
                currency?: string;
                /** Format: date-time */
                paidOn?: string | null;
                /** @enum {string} */
                status?: "paid" | "pending" | "failed";
            }[];
        };
        RazorpayOrder: {
            orderId?: string;
            /** @description In paise */
            amount?: number;
            /** @example INR */
            currency?: string;
            razorpayKeyId?: string;
            receipt?: string;
        };
        WorkoutSummary: {
            id?: string;
            title?: string;
            assignedBy?: string | null;
            exerciseCount?: number;
        };
        Workout: {
            id?: string;
            title?: string;
            assignedBy?: string | null;
            exercises?: {
                id?: string;
                name?: string;
                targetSets?: number;
                targetReps?: number;
                mediaUrl?: string | null;
                lastLog?: components["schemas"]["SetLog"];
            }[];
        };
        SetLog: {
            exerciseId?: string;
            setNumber?: number;
            reps?: number;
            weight?: number;
            /**
             * @default kg
             * @enum {string}
             */
            unit: "kg" | "lb";
        };
        WorkoutLogResult: {
            logId?: string;
            newPersonalRecords?: {
                exerciseId?: string;
                weight?: number;
            }[];
        };
        ClassSummary: {
            id?: string;
            title?: string;
            /** Format: date-time */
            startsAt?: string;
            seatsLeft?: number;
        };
        Progress: {
            latest?: {
                weightKg?: number | null;
                bmi?: number | null;
                bodyFatPct?: number | null;
            };
            series?: components["schemas"]["BodyMetric"][];
            photos?: {
                id?: string;
                /** @description Signed */
                url?: string;
                /** Format: date-time */
                takenAt?: string;
            }[];
        };
        BodyMetricInput: {
            weightKg?: number;
            waistCm?: number;
            /** Format: date-time */
            recordedAt?: string;
        };
        BodyMetric: {
            id?: string;
            weightKg?: number | null;
            bmi?: number | null;
            waistCm?: number | null;
            /** Format: date-time */
            recordedAt?: string;
        };
        UploadTarget: {
            photoId?: string;
            /** @description Signed PUT URL */
            uploadUrl?: string;
            expiresIn?: number;
        };
    };
    responses: {
        /** @description Phone is not linked to any gym membership */
        NotAMember: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rejected (e.g., duplicate / stale / capacity) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Client-generated key. Server dedupes retries (offline outbox). */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
