-- ============================================================
-- Migration: dashboard_briefings
--
-- Stores AI-generated daily briefings (Wave 5 of the World #1
-- Dashboard plan). One row per (gym, date). Generated by a 6 AM
-- cron, served instantly by GET /dashboard/briefing.
--
-- Run: psql $DATABASE_URL -f migration.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS "studio_template"."dashboard_briefings" (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    gym_id          UUID NOT NULL,
    branch_id       UUID,
    briefing_date   DATE NOT NULL,
    summary         TEXT NOT NULL,
    headline        TEXT,
    metrics         JSONB,                -- snapshot of metrics used to generate
    recommendations JSONB,                -- structured list: [{title, action_id?, why}]
    model           TEXT,                 -- e.g. 'claude-sonnet-4-20250514'
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_briefing UNIQUE (gym_id, briefing_date, branch_id)
);

CREATE INDEX IF NOT EXISTS idx_briefings_gym_date
    ON "studio_template"."dashboard_briefings" (gym_id, briefing_date DESC);

-- Apply to all existing tenant schemas
DO $$
DECLARE
    schema_name TEXT;
BEGIN
    FOR schema_name IN
        SELECT nspname FROM pg_namespace WHERE nspname LIKE 'studio_%' AND nspname != 'studio_template'
    LOOP
        EXECUTE format('
            CREATE TABLE IF NOT EXISTS %I.dashboard_briefings (
                id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                gym_id          UUID NOT NULL,
                branch_id       UUID,
                briefing_date   DATE NOT NULL,
                summary         TEXT NOT NULL,
                headline        TEXT,
                metrics         JSONB,
                recommendations JSONB,
                model           TEXT,
                generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                CONSTRAINT uq_briefing_%I UNIQUE (gym_id, briefing_date, branch_id)
            );
            CREATE INDEX IF NOT EXISTS idx_briefings_gym_date_%I
                ON %I.dashboard_briefings (gym_id, briefing_date DESC);
        ', schema_name, schema_name, schema_name, schema_name);
    END LOOP;
END $$;
